CREATE OR REPLACE FUNCTION CalculateAge(dob DATE)
RETURN NUMBER IS
  age NUMBER;
BEGIN
  age := FLOOR(MONTHS_BETWEEN(SYSDATE, dob) / 12);
  RETURN age;
END;
/
--example
SELECT CalculateAge(TO_DATE('2000-01-15', 'YYYY-MM-DD')) AS age FROM dual;
